/**
 * DO NOT EDIT THIS FILE DIRECTLY!
 *
 * This file is automatically edited when running `tsci dev` and dragging things
 * around. `tsci dev` searches for a file named "*.manual-edits.ts" and edits
 * it when you e.g. move a footprint. If there are multiple files, it'll try
 * to pick one based on context or ask.
 *
 * If you're not running `tsci dev`, you can safely edit this file.
 */
export default {
  // Generated when this file is created, this unique identifier is used to help
  // determine which file to edit when there are many *.manual-edits.ts files
  manual_edit_id: "abcdef",

  // Manual pcb placements, added when you drag a footprint
  pcb_placements: [
      {
        "_edit_event_id": "0.3120710594212608",
        "selector": ".B1",
        "center": {
          "x": 0.8328844469698069,
          "y": -4.004216322742135
        },
        "relative_to": "group_center"
      }
    ],
    edit_events: [],
    manual_trace_hints: [
      {
        "pcb_port_selector": ".B1 > .PWR",
        "offsets": [
          {
            "x": -0.9541573849097844,
            "y": 0.132457433925115,
            "via": false
          }
        ]
      }
    ]
}